### ISSUE TITLE
Converting object to an encodable object failed: Instance of 'Object'

### ISSUE THREAD

**Issue by SittiphanSittisak** [jonataslaw/get_storage#102]
I try to save List of object by GetStorage().write() but it's error.
Is it impossible to save objects?

```
Error: Converting object to an encodable object failed: Instance of 'Object'
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale th-TH)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by SittiphanSittisak** [comment]
It's not about this pk. It's about JSON.
This package save data by JSON encoded, and The jsonEncode can't convert the object.
We need to create the function in the class of an object for JSON conversion. 

First, this function for JSON encoding (className/object name is Obj).
Obj.fromJson(Map<String, dynamic> json)
      : obj1 = json['obj1'],
        obj2 = json['obj2'];

Last, this function for JSON decode.
  Map<String, dynamic> toJson() {
    return {
      'obj1': obj1,
      'obj2': obj2,
    };
  }

**Comment by SittiphanSittisak** [comment]
Hi, I found a new issue but it's the same issue.
After I close and open it again, the data from get_storage was changed.

Example:
```
GetStorage().write("test", [Obj(obj1:true,obj2:"true")]);
print(GetStorage().read("test"));     //[Instance of 'Obj']
//Close the program, Open the program
print(GetStorage().read("test"));     //[{"obj1":true, "obj2": "true"}]
```

Now, I need to use a function that looks like this:
```
  List<Obj> fromJson(List<Map<String, dynamic>> json) {
    return json.map().toList((e)=>Obj(obj1:e['obj1'],obj2:e['obj2'])); 
  }
```

Hope it will fix with a simple solution.

**Comment by mfurkanyuceal** [comment]
I am also having the same issue.

**Comment by d-apps** [comment]
I think you are making a mistake, always make sure you are storing data supported by GetStorage.

I have a lots of Maps with inner and inner maps, int, bool, List inside and I never had this issue. 

I think you are not converting your objects correctly when storing. Make sure you do a Class.toJson and storing right data before retrieving.

**Comment by LamesSY** [comment]
i am also having the sam issue.
`
static UserInfo? get user {
    var m = _box.read(_userInfoKey);
    if (m == null) return null;
    LogKit.i("read is UserInfo = ${m is UserInfo}");
    if (m is UserInfo) return m;
    return UserInfo.fromJson(m);
  }

`
log print 'read is UserInfo = false' after app restart, but it is true before restart

**Comment by LamesSY** [comment]
i am also having the sam issue.
```
static UserInfo? get user {
  var m = _box.read(_userInfoKey);
  if (m == null) return null;
  LogKit.i("read is UserInfo = ${m is UserInfo}");
  if (m is UserInfo) return m;
  return UserInfo.fromJson(m);
}
```
log print `read is UserInfo = true` before app restart,
log print `read is UserInfo = false` after app restart,

**Comment by RANEEMFAHMAWII** [comment]
i am also having the same issue.

`  List<VerifiedOrderModel> verifiedOrderItem = [];
VerifiedOrderModel verifiedOrderModel = VerifiedOrderModel(
            itemId: itemId,
            weightController: weightController.text,
            quantityController: quantityController.text,
            imageWeight: imageWeight!,
            imageItem: imageItem!);

        if (box.read("orderItems") == null) {
          verifiedOrderItem.add(verifiedOrderModel);
          box.write("orderItems", verifiedOrderItem);
          loggerServices.logger.i("First Time");

          Get.back(result: "success");
        }`

the log is:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Converting object to an encodable object failed: Instance of 'VerifiedOrderModel'
E/flutter (19561): #0      _JsonStringifier.writeObject (dart:convert/json.dart:794:7)
E/flutter (19561): #1      _JsonStringifier.writeList (dart:convert/json.dart:842:7)
E/flutter (19561): #2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:824:7)
E/flutter (19561): #3      _JsonStringifier.writeObject (dart:convert/json.dart:785:9)
E/flutter (19561): #4      _JsonStringifier.writeMap (dart:convert/json.dart:875:7)
E/flutter (19561): #5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:830:21)
E/flutter (19561): #6      _JsonStringifier.writeObject (dart:convert/json.dart:785:9)
E/flutter (19561): #7      _JsonStringStringifier.printOn (dart:convert/json.dart:983:17)
E/flutter (19561): #8      _JsonStringStringifier.stringify (dart:convert/json.dart:968:5)
E/flutter (19561): #9      JsonEncoder.convert (dart:convert/json.dart:345:30)
E/flutter (19561): #10     JsonCodec.encode (dart:convert/json.dart:231:45)
E/flutter (19561): #11     StorageImpl.flush (package:get_storage/src/storage/io.dart:34:37)
E/flutter (19561): #12     GetStorage._flush (package:get_storage/src/storage_impl.dart:144:23)
E/flutter (19561): #13     GetQueue._check (package:get/get_utils/src/queue/get_queue.dart:42:47)
E/flutter (19561): #14     GetQueue.add (package:get/get_utils/src/queue/get_queue.dart:29:5)
E/flutter (19561): #15     GetStorage._addToQueue (package:get_storage/src/storage_impl.dart:139:18)
E/flutter (19561): #16     Microtask.exec.<anonymous closure> (package:get_storage/src/storage_impl.dart:174:17)
E/flutter (19561): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (19561): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

its work fine but the printed in terminal when there is no issue

**Comment by d-apps** [comment]
> i am also having the same issue.
> 
> ```
>          `List<VerifiedOrderModel> verifiedOrderItem = [];
>          VerifiedOrderModel verifiedOrderModel = VerifiedOrderModel(
>         itemId: itemId,
>         weightController: weightController.text,
>         quantityController: quantityController.text,
>         imageWeight: imageWeight!,
>         imageItem: imageItem!);
> 
>     if (box.read("orderItems") == null) {
>       verifiedOrderItem.add(verifiedOrderModel);
>       box.write("orderItems", verifiedOrderItem);
>       loggerServices.logger.i("First Time");
> 
>       Get.back(result: "success");
>     }`
> ```
> 
> the log is: `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Converting object to an encodable object failed: Instance of 'VerifiedOrderModel' E/flutter (19561): #0 _JsonStringifier.writeObject (dart:convert/json.dart:794:7) E/flutter (19561): #1 _JsonStringifier.writeList (dart:convert/json.dart:842:7) E/flutter (19561): #2 _JsonStringifier.writeJsonValue (dart:convert/json.dart:824:7) E/flutter (19561): #3 _JsonStringifier.writeObject (dart:convert/json.dart:785:9) E/flutter (19561): #4 _JsonStringifier.writeMap (dart:convert/json.dart:875:7) E/flutter (19561): #5 _JsonStringifier.writeJsonValue (dart:convert/json.dart:830:21) E/flutter (19561): #6 _JsonStringifier.writeObject (dart:convert/json.dart:785:9) E/flutter (19561): #7 _JsonStringStringifier.printOn (dart:convert/json.dart:983:17) E/flutter (19561): #8 _JsonStringStringifier.stringify (dart:convert/json.dart:968:5) E/flutter (19561): #9 JsonEncoder.convert (dart:convert/json.dart:345:30) E/flutter (19561): #10 JsonCodec.encode (dart:convert/json.dart:231:45) E/flutter (19561): #11 StorageImpl.flush (package:get_storage/src/storage/io.dart:34:37) E/flutter (19561): #12 GetStorage._flush (package:get_storage/src/storage_impl.dart:144:23) E/flutter (19561): #13 GetQueue._check (package:get/get_utils/src/queue/get_queue.dart:42:47) E/flutter (19561): #14 GetQueue.add (package:get/get_utils/src/queue/get_queue.dart:29:5) E/flutter (19561): #15 GetStorage._addToQueue (package:get_storage/src/storage_impl.dart:139:18) E/flutter (19561): #16 Microtask.exec.<anonymous closure> (package:get_storage/src/storage_impl.dart:174:17) E/flutter (19561): #17 _microtaskLoop (dart:async/schedule_microtask.dart:40:21) E/flutter (19561): #18 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`
> 
> its work fine but the printed in terminal when there is no issue

Are you trying to store a` List<VerifiedOrderModel>`?
Because get_storage does not support custom classes, you need to convert it to Map first and then you will be able to store and retrieve correctly:

```
final List<Map> convertedList = verifiedOrderItem.map((item) => item.toJson()).toList();
box.write("orderItems", convertedList);

final listOfMaps = box.read("orderItems");
List<VerifiedOrderModel> verifiedOrderItem = listOfMaps.map((json) => VerifiedOrderModel.fromJson(json)).toList();
```
