### ISSUE TITLE
flutter getStorage throw MissingPluginException in unit test

### ISSUE THREAD

**Issue by tazik561** [jonataslaw/get_storage#109]
I am using getStorage on my project. Now I am trying to write unit test and inside test method I wrote `await GetStorage.init();`:

    void main() async {
      TestWidgetsFlutterBinding.ensureInitialized();
    
      setUpAll(() {});
    
      group('init_getx', () {
        test(
          'Init Getx test',
          () async {
            await GetStorage.init();

but after running test I got this error :

    MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_macos)

how can I fix this problem?

I also tried this 
```
void main() async {
  TestWidgetsFlutterBinding.ensureInitialized();

  const channel = MethodChannel('plugins.flutter.io/path_provider');
  void setUpMockChannels(MethodChannel channel) {
    channel.setMockMethodCallHandler((MethodCall methodCall) async {
      if (methodCall.method == 'getApplicationDocumentsDirectory') {
        return '.';
      }
    });
  }
  setUpAll(() async {
    setUpMockChannels(channel);
  });
  
  setUp(() async {
    await GetStorage.init();
  });
```
But I still got error?

**Comment by tejpalSinghRathore** [comment]
were you able to solve it
?

**Comment by tazik561** [comment]
yes, I removed `await GetStorage.init();` from my classes that were under-tested, and put it in the main dart. and In my class, I used `myvaraible = GetStorage() `t o using if getx storage instance. and in test I used mock of getxStorage object

**Comment by tejpalSinghRathore** [comment]
> 

if I run the application in release mode I am getting the same error, can you please suggest a solution to that

main.dart :  

main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await GetStorage.init();
  runApp(MyApp());
}


----------------------in release mode-----------------------------------
 [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (11436): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:47)
E/flutter (11436): <asynchronous suspension>
E/flutter (11436): #1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:28)
E/flutter (11436): <asynchronous suspension>
E/flutter (11436): #2      main (package:inunison/main.dart:14)
E/flutter (11436): <asynchronous suspension>
E/flutter (11436):

**Comment by tazik561** [comment]
which platform are you using?

**Comment by tejpalSinghRathore** [comment]
Android

**Comment by tejpalSinghRathore** [comment]
this can be solved by putting some changes in build.gradle under

android {
buildTypes {
getByName("release") {
// Enables code shrinking, obfuscation, and optimization for only
// your project's release build type.
isMinifyEnabled = true

        // Enables resource shrinking, which is performed by the
        // Android Gradle plugin.
        isShrinkResources = true

        // Includes the default ProGuard rules files that are packaged with
        // the Android Gradle plugin. To learn more, go to the section about
        // R8 configuration files.
        proguardFiles(
            getDefaultProguardFile("proguard-android-optimize.txt"),
            "proguard-rules.pro"
        )
    }
}
...
}

reference: https://developer.android.com/studio/build/shrink-code#kts

**Comment by amalnaami** [comment]
any update regarding thus issue?

**Comment by SeongUgJung** [comment]
I got this hint from path_provider 
and it seems that worked as well in mac-os (my local machine), ubuntu (CI machine)

https://github.com/flutter/plugins/blob/main/packages/path_provider/path_provider_foundation/test/messages_test.g.dart#L24

```
void main() {
  void setUpMockChannels() {
    const MessageCodec<Object?> codec = StandardMessageCodec();
    const BasicMessageChannel<Object?> channel =
        BasicMessageChannel<Object?>('dev.flutter.pigeon.PathProviderApi.getDirectoryPath', codec);

    channel.setMockMessageHandler((Object? message) async {
      const String output = '.';
      return <Object?>[output];
    });
  }

  setUpAll(() {
    setUpMockChannels();
  });
}
```

**Comment by Pify** [comment]
> I got this hint from path_provider and it seems that worked as well in mac-os (my local machine), ubuntu (CI machine)
> 
> https://github.com/flutter/plugins/blob/main/packages/path_provider/path_provider_foundation/test/messages_test.g.dart#L24
> 
> ```
> void main() {
>   void setUpMockChannels() {
>     const MessageCodec<Object?> codec = StandardMessageCodec();
>     const BasicMessageChannel<Object?> channel =
>         BasicMessageChannel<Object?>('dev.flutter.pigeon.PathProviderApi.getDirectoryPath', codec);
> 
>     channel.setMockMessageHandler((Object? message) async {
>       const String output = '.';
>       return <Object?>[output];
>     });
>   }
> 
>   setUpAll(() {
>     setUpMockChannels();
>   });
> }
> ```

have you try to add path_provider dependency to your project ? i have try it and it works

**Comment by ghost** [comment]
for anyone interested how to get it working now see [this](https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider/test/path_provider_test.dart), in short you need to mock `PathProviderPlatform`
