### ISSUE TITLE
HashSet support?

### ISSUE THREAD

**Issue by LBYPatrick** [jonataslaw/get_storage#113]
Hi,

I was attempting to write a ``HashSet<String>`` object to ``get_storage`` like so:

```dart
final hSet = HashSet<String>();

hSet.add("foo");
hSet.add("bar");

GetStorage().write("some_key", hSet);
```

But this error would occur and prevent ``get_stroage`` from writing to the persistent storage but leaving it in RAM:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Converting object to an encodable object failed: Instance of '_HashSet<String>'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:792:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:873:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:828:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:783:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:981:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:966:5)
#6      JsonEncoder.convert (dart:convert/json.dart:345:30)
#7      JsonCodec.encode (dart:convert/json.dart:231:45)
...
```

Or should I use ``List<String>`` instead? But doing so would result in some O(N) access time in my other piece of code, which does not sound good...

**Comment by kaitotokyo** [comment]
I met same issue as you, 
and I notice that get_storage using JSON as the serial format, Json use []/array to store the data which means it unable to distinguish whether it is a set or a list.
So, the answer is Yes.
