### ISSUE TITLE
PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))

### ISSUE THREAD

**Issue by summer-07** [jonataslaw/get_storage#132]
[ +192 ms] E/flutter (19963): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
[        ] E/flutter (19963): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:49:7)
[        ] E/flutter (19963): <asynchronous suspension>
[        ] E/flutter (19963): #1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:30:7)
[        ] E/flutter (19963): <asynchronous suspension>
[        ] E/flutter (19963): #2      init (package:front_satoshi_ai/main.dart:16:3)
[        ] E/flutter (19963): <asynchronous suspension>
[        ] E/flutter (19963): #3      main (package:front_satoshi_ai/main.dart:20:3)
[        ] E/flutter (19963): <asynchronous suspension>
[        ] E/flutter (19963):

**Comment by Wing-Li** [comment]
+1 
Appeared suddenly, never before

**Comment by Wing-Li** [comment]
我打开 Android项目 重新编译一下 gradle ，然后就好了。
你可以尝试一下。

**Comment by summer-07** [comment]
好的，谢谢

**Comment by palorotolo** [comment]
> 我打开 Android项目 重新编译一下 gradle ，然后就好了。 你可以尝试一下。

还是不行，感觉是和项目自己的flutter和android通讯代码冲突了。

**Comment by YeFei572** [comment]
> > 我打开 Android项目 重新编译一下 gradle ，然后就好了。 你可以尝试一下。
> 
> 还是不行，感觉是和项目自己的flutter和android通讯代码冲突了。

貌似是这么回事，你怎么解决的呢？

**Comment by MonoKelvin** [comment]
> 我打开 Android项目 重新编译一下 gradle ，然后就好了。 你可以尝试一下。

还真是，多谢！！！
