### ISSUE TITLE
Unable to call GetStorage.init() inside Isolate

### ISSUE THREAD

**Issue by binoytv9** [jonataslaw/get_storage#82]
How can I use GetStorage inside an Isolate? I have tried as shown below, but getting error 'UI actions are only available on root isolate.' 

Code:
`
void run(_) async {
  await GetStorage.init();

  print(Get.put<PreferenceService>(GetStoragePreferenceImp())
      .get(Constants.BOOT_SCREEN));
}

Future<void> execute() async {
    await Isolate.spawn(run, 0);
  }
`

Stack Trace:
[VERBOSE-2:dart_isolate.cc(1138)] Unhandled exception:
UI actions are only available on root isolate.
#0      PlatformDispatcher._nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:446:59)
#1      PlatformDispatcher.onReportTimings= (dart:ui/platform_dispatcher.dart:438:29)
#2      SingletonFlutterWindow.onReportTimings= (dart:ui/window.dart:540:24)
#3      SchedulerBinding.addTimingsCallback
package:flutter/…/scheduler/binding.dart:265
#4      SchedulerBinding.initInstances
package:flutter/…/scheduler/binding.dart:205
#5      ServicesBinding.initInstances
package:flutter/…/services/binding.dart:32
#6      PaintingBinding.initInstances
package:flutter/…/painting/binding.dart:22
#7      SemanticsBinding.initInstances
package:flutter/…/semantics/binding.dart:22
#8      RendererBinding.initInstances
package:flutter/…/rendering/binding.dart:28
#9      WidgetsBinding.initInstances
package:flutter/…/widgets/binding.dart:277
#10     new BindingBase <…>

**Comment by briankariuki** [comment]
I guess you could initialize it in the UI isolate then pass it to your isolate

**Comment by moldstadt** [comment]
> I guess you could initialize it in the UI isolate then pass it to your isolate

I have tried this, but I get the following error if I try to pass the GetStorage instance to the isolate. 

> Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:io' Class: _RandomAccessFileOpsImpl

Has anyone got a solution for this?

**Comment by geoffreyLB** [comment]
Any updates on this issue, I am facing same error
