### ISSUE TITLE
[BUG] Error on GetStorage.init();

### ISSUE THREAD

**Issue by gaetan1903** [jonataslaw/get_storage#88]
```dart
void main() async {
  await GetStorage.init();
  // await dotenv.load();
  runApp(MyApp());
}
```
```error
MissingPluginException (MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider))
```

```s
E/flutter (10909): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on
channel plugins.flutter.io/path_provider)
[        ] E/flutter (10909): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:47:7)
[        ] E/flutter (10909): <asynchronous suspension>
[        ] E/flutter (10909): #1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:28:7)
[        ] E/flutter (10909): <asynchronous suspension>
[        ] E/flutter (10909): #2      main (package:bjj_library/main.dart:18:3)
[        ] E/flutter (10909): <asynchronous suspension>
[        ] E/flutter (10909): 

```

**Comment by gaetan1903** [comment]
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (il y a 2 mois) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

**Comment by gaetan1903** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Arch Linux 5.15.10-arch1-1, locale fr_FR.UTF-8)
    • Flutter version 2.5.3 at /home/gaetan1903/environnements/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (il y a 2 mois), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/gaetan1903/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/gaetan1903/environnements/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.0
    • cmake version 3.22.1
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/gaetan1903/environnements/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • Redmi Note 9 Pro Max (mobile) • 213b45b0 • android-arm64  • Android 11 (API 30)
    • Linux (desktop)               • linux    • linux-x64      • Arch Linux 5.15.10-arch1-1
    • Chrome (web)                  • chrome   • web-javascript • Chromium 96.0.4664.110 Arch Linux

• No issues found!

**Comment by gaetan1903** [comment]
get_storage:
    dependency: "direct main"
    description:
      name: get_storage
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"

**Comment by gaetan1903** [comment]
`flutter upgrade` fix it.
