### ISSUE TITLE
Get storage not working when use 'FlutterFragmentActivity' in main activity

### ISSUE THREAD

**Issue by AlirezaDaryani** [jonataslaw/get_storage#90]
In my project, I used `local_auth` and I must change extends of main activity to `FlutterFragmentActivity`.

After this change, android run make this issue :

       E/flutter (18075): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No 
       implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
       E/flutter (18075): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:47:7)
       E/flutter (18075): <asynchronous suspension>
       E/flutter (18075): #1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:28:7)
       E/flutter (18075): <asynchronous suspension>
       E/flutter (18075): #2      main (package:somi_flutter_app/main.dart:25:3)
       E/flutter (18075): <asynchronous suspension>

How can I fix this issue?
Why get storage depends on `FlutterActivity`?

**Comment by loic-hamdi** [comment]
Facing the same issue, did you find a workaround?
